[wokwi]
version = 1
firmware = ".pio/build/esp32dev/firmware.bin"
elf = ".pio/build/esp32dev/firmware.elf"
partitions = "storage.csv" # Utiliser la table de partitions personnalisée

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"

[wokwi.esp32.filesystem] # Restauré pour fournir les fichiers web à la simulation
"/" = "./data"

# [wokwi.littlefs] # Section supprimée pour forcer l'utilisation de la partition table
# "style.css" = "data/style.css"
# "index.html" = "data/index.html"
